### ISSUE TITLE
@include bg-variant(".bg-#{$color}", $value, true); Build Failure

### ISSUE THREAD

**Issue by brentvdalling** [akaunting/akaunting#1276]
The "npm run dev" step is failing on a fresh install. I've gone through similar issues in this repo and tried those solutions. But nothing is working for me. 

### Steps to reproduce the issue
follow the basic installation instructions on a lamp stack Ubuntu 18.04 machine with npm version: 

### Expected result
It should compile correctly so we can use the vue components and the styling.

### Actual result
Failure.

### System information (Akaunting, PHP versions)
Akaunting 2.0.1

### Error
```
ERROR in ./resources/assets/sass/argon.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

  @include bg-variant(".bg-#{$color}", $value, true);
          ^
      Wrong number of arguments (3 for 2) for `bg-variant'
      in /node_modules/bootstrap/scss/utilities/_background.scss (line 4, column 12)
    at runLoaders (/node_modules/webpack/lib/NormalModule.js:316:20)
    at /node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.render [as callback] (/node_modules/sass-loader/dist/index.js:89:7)
    at Object.done [as callback] (/node_modules/neo-async/async.js:8067:18)
    at options.error (/node_modules/node-sass/lib/index.js:294:32)
 @ ./resources/assets/sass/argon.scss

ERROR in ./resources/assets/sass/argon.scss (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/dist/cjs.js??ref--5-5!./resources/assets/sass/argon.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

  @include bg-variant(".bg-#{$color}", $value, true);
          ^
      Wrong number of arguments (3 for 2) for `bg-variant'
      in /node_modules/bootstrap/scss/utilities/_background.scss (line 4, column 12)
 @ ./resources/assets/sass/argon.scss 2:14-267
npm ERR! Linux 4.15.0-76-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "development"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! akaunting@2.0.0 development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the akaunting@2.0.0 development script 'cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the akaunting package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs akaunting
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls akaunting
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log

npm ERR! Linux 4.15.0-76-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
npm ERR! node v8.10.0
```

**Comment by aliuysal60** [comment]
Yes i have this problem too

**Comment by brentvdalling** [comment]
I have still not found a fix for this.

**Comment by jashk** [comment]
I solve this using a node 10 version using [nvm ](https://github.com/nvm-sh/nvm)
Try 
```
node --version
npm cache clear --force
npm install
npm run dev
```

**Comment by brentvdalling** [comment]
I'm going to leave this open until someone can verify the fix works that @jashk suggested. I moved on to a paid accounting platform from code canyon. (And I'm heavily modifying it because it sucks. Code canyon stuff is half baked at best). But I do not want to close the ticket just yet if others in the community are experiencing this issue. I may sometime this weekend make a test setup on valet and see if it works or not. Thank you @jashk for your response.
