### ISSUE TITLE
Fresh install akaunting 2.0 error

### ISSUE THREAD

**Issue by MarkosAg** [akaunting/akaunting#1472]
Hello guys, nice work first to all.

### Steps to reproduce the issue
npm run dev after installing all dependencies.

### Expected result
successful app run

### Actual result

```
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

95% emitting unnamed compat pluginnpm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! akaunting@2.0.0 development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the akaunting@2.0.0 development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-06T20_03_28_813Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! akaunting@2.0.0 dev: `npm run development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the akaunting@2.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-06T20_03_28_846Z-debug.log
```

### System information (Akaunting, PHP versions)
Akaunting 2.0
Php v7.2.24
Fresh install on ubuntu0.18.04
mysql  Ver 14.14 Distrib 5.7.30

### Additional comments
Changed from node  v14.4.0 -> v10.21.0 and same result. 

Any suggestions?

Full error log

```
0 info it worked if it ends with ok
1 verbose cli [ '/root/.nvm/versions/node/v10.21.0/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v10.21.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'development' ]
2 info using npm@6.14.5
3 info using node@v10.21.0
4 verbose run-script [ 'predevelopment', 'development', 'postdevelopment' ]
5 info lifecycle akaunting@2.0.0~predevelopment: akaunting@2.0.0
6 info lifecycle akaunting@2.0.0~development: akaunting@2.0.0
7 verbose lifecycle akaunting@2.0.0~development: unsafe-perm in lifecycle true
8 verbose lifecycle akaunting@2.0.0~development: PATH: /root/.nvm/versions/node/v10.21.0/lib/node_modules/npm/node_modules/npm-lifecycle/no$
9 verbose lifecycle akaunting@2.0.0~development: CWD: /var/www/html/ak/akaunting
10 silly lifecycle akaunting@2.0.0~development: Args: [ '-c',
10 silly lifecycle   'cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/la$
11 silly lifecycle akaunting@2.0.0~development: Returned: code: 1  signal: null
12 info lifecycle akaunting@2.0.0~development: Failed to exec development script
13 verbose stack Error: akaunting@2.0.0 development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-$
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v10.21.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.j$
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v10.21.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spa$
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid akaunting@2.0.0
15 verbose cwd /var/www/html/ak/akaunting
16 verbose Linux 4.15.0-101-generic
17 verbose argv "/root/.nvm/versions/node/v10.21.0/bin/node" "/root/.nvm/versions/node/v10.21.0/bin/npm" "run" "development"
18 verbose node v10.21.0
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error akaunting@2.0.0 development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --confi$
22 error Exit status 1
23 error Failed at the akaunting@2.0.0 development script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by aslamsayyed** [comment]
Have you found the solution ?

**Comment by stevefab** [comment]
i have the same problem

**Comment by MarkosAg** [comment]
I ended installing it vía Digital Ocean marketplace. lmao.

**Comment by ArbenKarb** [comment]
same here

**Comment by tahertechs** [comment]
Delete ```node_modules ``` folder
Run ```npm install --global cross-env```
Run ```npm install --no-bin-links```
Run ```npm run dev```

Done. It should be working pretty fine.

For More Read [HERE](https://stackoverflow.com/questions/45034581/laravel-5-4-cross-env-is-not-recognized-as-an-internal-or-external-command)

**Comment by denisdulici** [comment]
Fixed in the latest version.
