### ISSUE TITLE
Customer Encounter Error When Select Payment Method Inside portal/invoices/{show}

### ISSUE THREAD

**Issue by syahrinseth** [akaunting/akaunting#1679]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue

1. Login As Customer
2. Go to the invoices page and select the unpaid invoice to view the invoice.
3. Select Payment Method
4. Got an error on an ajax request after selecting the payment method.

### Actual result

```
[previous exception] [object] (ErrorException(code: 0): Undefined index: code at /Users/syahrinseth/Documents/Documents – Syahrin’s MacBook Pro/valet/akaunting/storage/framework/views/a8c8002efc4a3c713ef25900716bf1afd05c072d.php:29)
[stacktrace]
#0 /Users/syahrinseth/Documents/Documents – Syahrin’s MacBook Pro/valet/akaunting/storage/framework/views/a8c8002efc4a3c713ef25900716bf1afd05c072d.php(29): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined index...', '/Users/syahrins...', 29, Array)
#1 /Users/syahrinseth/Documents/Documents – Syahrin’s MacBook Pro/valet/akaunting/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(41): include('/Users/syahrins...')
#2 /Users/syahrinseth/Documents/Documents – Syahrin’s MacBook Pro/valet/akaunting/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(57): Illuminate\\View\\Engines\\PhpEngine->evaluatePath('/Users/syahrins...', Array)
#3 /Users/syahrinseth/Documents/Documents – Syahrin’s MacBook Pro/valet/akaunting/vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(37): Illuminate\\View\\Engines\\CompilerEngine->get('/Users/syahrins...', Array)
#4 /Users/syahrinseth/Documents/Documents – Syahrin’s MacBook Pro/valet/akaunting/vendor/laravel/framework/src/Illuminate/View/View.php(139): Facade\\Ignition\\Views\\Engines\\CompilerEngine->get('/Users/syahrins...', Array)
#5 /Users/syahrinseth/Documents/Documents – Syahrin’s MacBook Pro/valet/akaunting/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#6 /Users/syahrinseth/Documents/Documents – Syahrin’s MacBook Pro/valet/akaunting/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#7 /Users/syahrinseth/Documents/Documents – Syahrin’s MacBook Pro/valet/akaunting/modules/OfflinePayments/Http/Controllers/Payment.php(32): Illuminate\\View\\View->render()
#8 [internal function]: Modules\\OfflinePayments\\Http\\Controllers\\Payment->show(Object(App\\Models\\Sale\\Invoice), Object(App\\Http\\Requests\\Portal\\InvoicePayment))
#9 /Users/syahrinseth/Documents/Documents – Syahrin’s MacBook Pro/valet/akaunting/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#10 /Users/syahrinseth/Documents/Documents – Syahrin’s MacBook Pro/valet/akaunting/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('show', Array)
#11 /Users/syahrinseth/Documents/Documents – Syahrin’s MacBook Pro/valet/akaunting/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Modules\\OfflinePayments\\Http\\Controllers\\Payment), 'show')
```

### System information (Akaunting, PHP versions)

Akaunting ver 2.0.26
PHP ver 7.3.8

**Comment by cuneytsenturk** [comment]
this issue fixed latest version.
