### ISSUE TITLE
Unable to install plugin on premise after clean v3.0.3 install

### ISSUE THREAD

**Issue by Geod24** [akaunting/akaunting#2523]
### Akaunting version

v3.0.3

### PHP version

v8.1.0

### Operating system

Ubuntu 22.04.0 

### Steps to reproduce

Installed a new Akaunting instance, set up the API key after initial setup, whenever I click on "Double Entry" (a plugin I have previously purchased), I get a 500.

### Expected result

Things to work

### Actual result

500 / Internal server error

The above logs repeat multiple times.

### Relevant log output

```shell
[2022-07-07 18:15:52] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [deprecations] is not defined. at $ROOT/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:207)
[stacktrace]
#0 $ROOT/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(132): Illuminate\\Log\\LogManager->resolve()
#1 $ROOT/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(119): Illuminate\\Log\\LogManager->get()
#2 $ROOT/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(108): Illuminate\\Log\\LogManager->driver()
#3 $ROOT/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(122): Illuminate\\Log\\LogManager->channel()
#4 $ROOT/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(71): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleDeprecationError()
#5 $ROOT/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(257): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
[...]
```

```
[2022-07-07 18:15:52] laravel.WARNING: Return type of Akaunting\Menu\Menu::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in $ROOT/vendor/akaunting/laravel-menu/src/Menu.php on line 163  
[2022-07-07 18:15:52] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [deprecations] is not defined. at $ROOT/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:207)
[stacktrace]
#0 $ROOT/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(132): Illuminate\\Log\\LogManager->resolve()
#1 $ROOT/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(119): Illuminate\\Log\\LogManager->get()
[...]
```

```
[2022-07-07 18:15:52] laravel.WARNING: str_contains(): Passing null to parameter #1 ($haystack) of type string is deprecated in $ROOT/vendor/laravel/framework/src/Illuminate/Support/Str.php on line 229  
[2022-07-07 18:15:52] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [deprecations] is not defined. at $ROOT/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:207)
[stacktrace]
#0 $ROOT/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(132): Illuminate\\Log\\LogManager->resolve()
#1 $ROOT/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(119): Illuminate\\Log\\LogManager->get()
[...]
```
```

**Comment by serotonie** [comment]
Here it is :
`resources/views/components/layouts/modules/show/information.blade.php`
Just add an `@endif` after the first `@if` block
Like this:
`@if (! empty($module->plan))
    <div class="text-center text-sm mt-3 mb--2 bg-red-100 rounded-lg p-2 cursor-default">
        <span class="text-sm text-red-700">
            {!! trans('modules.only_premium_plan') !!}
        </span>
    </div>
@endif`

**Comment by StefanArts** [comment]
@serotonie I encountered the same error.
I created a pull request, it is an easy fix: https://github.com/akaunting/akaunting/pull/2527

**Comment by cuneytsenturk** [comment]
This issue solved latest package. You will wait 3.0.4 version.
