### ISSUE TITLE
Akaunting could not be run

### ISSUE THREAD

**Issue by nnq1** [akaunting/akaunting#2866]
### Akaunting version

3.0.11

### PHP version

8.2.0

### Operating system

MacOS Ventura Version 13.1

### Steps to reproduce

1-Install Akaunting from GitHub as instructed exactly.
2-run it on localhost by _**php artisan serve**_.

### Expected result

install and run Akaunting app

### Actual result

not opening Akaunting correctly as attached screen shot shows:
<img width="406" alt="image" src="https://user-images.githubusercontent.com/35674462/212031304-c4bc755d-e847-4d75-8d65-65acb2a8aaf4.png">
when I entered the credential I got this:
{"status":null,"success":true,"error":false,"message":"Verification done! You are being redirected...","data":null,"redirect":"http:\/\/127.0.0.1:8000\/1"}
After refresh and confirm I got white page of http://127.0.0.1:8000/1/wizard

### Additional comments

1. I tried https://akaunting.com/forum/discussion/installation-update and this issue has been submitted 6 months ago with out solving.
2. I repeated the process of installing several times, but got same result.
3. I contacted support of Akaunting a week ago, but no reply!
4. I tried installing by Docker https://hub.docker.com/r/akaunting/akaunting but no result.
5. tried https://akaunting.com/docs/installation

### Relevant log output

```shell
http://127.0.0.1:8000/auth/login
[2023-01-12 08:33:32] local.ERROR: SQLSTATE[HY000]: General error: 1826 Duplicate foreign key constraint name 'original_media_id' (SQL: alter table `nrd_media` add constraint `original_media_id` foreign key (`original_media_id`) references `nrd_media` (`id`) on delete set null) {"exception":"[object] (Illuminate\\Database\\QueryException(code: HY000): SQLSTATE[HY000]: General error: 1826 Duplicate foreign key constraint name 'original_media_id' (SQL: alter table `nrd_media` add constraint `original_media_id` foreign key (`original_media_id`) references `nrd_media` (`id`) on delete set null) at /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Connection.php:760)
[stacktrace]
#0 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\\Database\\Connection->runQueryCallback('alter table `nr...', Array, Object(Closure))
#1 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Connection.php(534): Illuminate\\Database\\Connection->run('alter table `nr...', Array, Object(Closure))
#2 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php(109): Illuminate\\Database\\Connection->statement('alter table `nr...')
#3 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(422): Illuminate\\Database\\Schema\\Blueprint->build(Object(Illuminate\\Database\\MySqlConnection), Object(Illuminate\\Database\\Schema\\Grammars\\MySqlGrammar))
#4 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(269): Illuminate\\Database\\Schema\\Builder->build(Object(Illuminate\\Database\\Schema\\Blueprint))
#5 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): Illuminate\\Database\\Schema\\Builder->table('media', Object(Closure))
#6 /Users/nabil/ws/akaunting/vendor/plank/laravel-mediable/migrations/2020_10_12_000000_add_variants_to_media.php(17): Illuminate\\Support\\Facades\\Facade::__callStatic('table', Array)
#7 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(481): AddVariantsToMedia->up()
#8 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(399): Illuminate\\Database\\Migrations\\Migrator->runMethod(Object(Illuminate\\Database\\MySqlConnection), Object(AddVariantsToMedia), 'up')
#9 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(408): Illuminate\\Database\\Migrations\\Migrator->Illuminate\\Database\\Migrations\\{closure}()
#10 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(209): Illuminate\\Database\\Migrations\\Migrator->runMigration(Object(AddVariantsToMedia), 'up')
#11 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Console/View/Components/Task.php(36): Illuminate\\Database\\Migrations\\Migrator->Illuminate\\Database\\Migrations\\{closure}()
#12 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(738): Illuminate\\Console\\View\\Components\\Task->render('2020_10_12_0000...', Object(Closure))
#13 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(209): Illuminate\\Database\\Migrations\\Migrator->write('Illuminate\\\\Cons...', '2020_10_12_0000...', Object(Closure))
#14 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(174): Illuminate\\Database\\Migrations\\Migrator->runUp('/Users/nabil/ws...', 1, false)
#15 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(117): Illuminate\\Database\\Migrations\\Migrator->runPending(Array, Array)
#16 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(88): Illuminate\\Database\\Migrations\\Migrator->run(Array, Array)
#17 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(615): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#18 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(81): Illuminate\\Database\\Migrations\\Migrator->usingConnection(NULL, Object(Closure))
#19 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#20 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#21 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#22 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#23 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#24 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\\Container\\Container->call(Array)
#25 /Users/nabil/ws/akaunting/vendor/symfony/console/Command/Command.php(291): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#26 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Console/Command.php(151): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#27 /Users/nabil/ws/akaunting/vendor/symfony/console/Application.php(1014): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#28 /Users/nabil/ws/akaunting/vendor/symfony/console/Application.php(301): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Database\\Console\\Migrations\\MigrateCommand), Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#29 /Users/nabil/ws/akaunting/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#30 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#31 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Console/Application.php(193): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#32 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(336): Illuminate\\Console\\Application->call('migrate', Array, NULL)
#33 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): Illuminate\\Foundation\\Console\\Kernel->call('migrate', Array)
#34 /Users/nabil/ws/akaunting/app/Utilities/Installer.php(161): Illuminate\\Support\\Facades\\Facade::__callStatic('call', Array)
#35 /Users/nabil/ws/akaunting/app/Console/Commands/Install.php(193): App\\Utilities\\Installer::createDbTables('localhost', '3306', 'akaunting', 'root', 'xsdxmysql', NULL)
#36 /Users/nabil/ws/akaunting/app/Console/Commands/Install.php(78): App\\Console\\Commands\\Install->createDatabaseTables()
#37 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\Install->handle()
#38 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#39 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#40 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#41 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#42 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\\Container\\Container->call(Array)
#43 /Users/nabil/ws/akaunting/vendor/symfony/console/Command/Command.php(291): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#44 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Console/Command.php(151): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#45 /Users/nabil/ws/akaunting/vendor/symfony/console/Application.php(1014): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#46 /Users/nabil/ws/akaunting/vendor/symfony/console/Application.php(301): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\Install), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#47 /Users/nabil/ws/akaunting/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#48 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#49 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#50 /Users/nabil/ws/akaunting/artisan(22): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#51 {main}

[previous exception] [object] (PDOException(code: HY000): SQLSTATE[HY000]: General error: 1826 Duplicate foreign key constraint name 'original_media_id' at /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Connection.php:545)
[stacktrace]
#0 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Connection.php(545): PDOStatement->execute()
#1 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Connection.php(753): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('alter table `nr...', Array)
#2 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\\Database\\Connection->runQueryCallback('alter table `nr...', Array, Object(Closure))
#3 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Connection.php(534): Illuminate\\Database\\Connection->run('alter table `nr...', Array, Object(Closure))
#4 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php(109): Illuminate\\Database\\Connection->statement('alter table `nr...')
#5 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(422): Illuminate\\Database\\Schema\\Blueprint->build(Object(Illuminate\\Database\\MySqlConnection), Object(Illuminate\\Database\\Schema\\Grammars\\MySqlGrammar))
#6 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(269): Illuminate\\Database\\Schema\\Builder->build(Object(Illuminate\\Database\\Schema\\Blueprint))
#7 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): Illuminate\\Database\\Schema\\Builder->table('media', Object(Closure))
#8 /Users/nabil/ws/akaunting/vendor/plank/laravel-mediable/migrations/2020_10_12_000000_add_variants_to_media.php(17): Illuminate\\Support\\Facades\\Facade::__callStatic('table', Array)
#9 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(481): AddVariantsToMedia->up()
#10 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(399): Illuminate\\Database\\Migrations\\Migrator->runMethod(Object(Illuminate\\Database\\MySqlConnection), Object(AddVariantsToMedia), 'up')
#11 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(408): Illuminate\\Database\\Migrations\\Migrator->Illuminate\\Database\\Migrations\\{closure}()
#12 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(209): Illuminate\\Database\\Migrations\\Migrator->runMigration(Object(AddVariantsToMedia), 'up')
#13 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Console/View/Components/Task.php(36): Illuminate\\Database\\Migrations\\Migrator->Illuminate\\Database\\Migrations\\{closure}()
#14 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(738): Illuminate\\Console\\View\\Components\\Task->render('2020_10_12_0000...', Object(Closure))
#15 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(209): Illuminate\\Database\\Migrations\\Migrator->write('Illuminate\\\\Cons...', '2020_10_12_0000...', Object(Closure))
#16 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(174): Illuminate\\Database\\Migrations\\Migrator->runUp('/Users/nabil/ws...', 1, false)
#17 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(117): Illuminate\\Database\\Migrations\\Migrator->runPending(Array, Array)
#18 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(88): Illuminate\\Database\\Migrations\\Migrator->run(Array, Array)
#19 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(615): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#20 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(81): Illuminate\\Database\\Migrations\\Migrator->usingConnection(NULL, Object(Closure))
#21 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#22 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#23 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#24 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#25 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#26 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\\Container\\Container->call(Array)
#27 /Users/nabil/ws/akaunting/vendor/symfony/console/Command/Command.php(291): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#28 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Console/Command.php(151): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#29 /Users/nabil/ws/akaunting/vendor/symfony/console/Application.php(1014): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#30 /Users/nabil/ws/akaunting/vendor/symfony/console/Application.php(301): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Database\\Console\\Migrations\\MigrateCommand), Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#31 /Users/nabil/ws/akaunting/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#32 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#33 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Console/Application.php(193): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#34 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(336): Illuminate\\Console\\Application->call('migrate', Array, NULL)
#35 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): Illuminate\\Foundation\\Console\\Kernel->call('migrate', Array)
#36 /Users/nabil/ws/akaunting/app/Utilities/Installer.php(161): Illuminate\\Support\\Facades\\Facade::__callStatic('call', Array)
#37 /Users/nabil/ws/akaunting/app/Console/Commands/Install.php(193): App\\Utilities\\Installer::createDbTables('localhost', '3306', 'akaunting', 'root', 'xsdxmysql', NULL)
#38 /Users/nabil/ws/akaunting/app/Console/Commands/Install.php(78): App\\Console\\Commands\\Install->createDatabaseTables()
#39 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\Install->handle()
#40 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#41 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#42 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#43 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#44 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\\Container\\Container->call(Array)
#45 /Users/nabil/ws/akaunting/vendor/symfony/console/Command/Command.php(291): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#46 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Console/Command.php(151): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#47 /Users/nabil/ws/akaunting/vendor/symfony/console/Application.php(1014): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#48 /Users/nabil/ws/akaunting/vendor/symfony/console/Application.php(301): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\Install), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#49 /Users/nabil/ws/akaunting/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#50 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#51 /Users/nabil/ws/akaunting/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#52 /Users/nabil/ws/akaunting/artisan(22): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#53 {main}
"} 

```

**Comment by nnq1** [comment]
I solve the issue by using Ngixn as web server.
