### ISSUE TITLE
erro 500 php 8.1 due to symphony issue

### ISSUE THREAD

**Issue by nephaste** [akaunting/akaunting#2915]
### Akaunting version

3.012

### PHP version

8.1.16

### Operating system

QNAP OS Linux

### Steps to reproduce

While all is working fine with PHP 8.0.27

porting on PHP 8.1.16 ... Akaunting installer doesnt start Apache goes in error 500

checking logs

look like there is an issue with symphony and php 8.1.x 

### Expected result

fix symphony error

### Actual result

[Akaunting81.log](https://github.com/akaunting/akaunting/files/10870699/Akaunting81.log)
full Apache log atttached

### Additional comments

same problem occur with PHP 8.2.3
only php 8.0.x works

### Relevant log output

```shell
[Thu Mar 02 12:08:34.303314 2023] [php:error] [pid 11648:tid 139906613344000] [client 192.168.0.117:57737] PHP Fatal error:  Declaration of Maatwebsite\\Excel\\Cache\\MemoryCache::get(string $key, mixed $default = null): mixed must be compatible with Psr\\SimpleCache\\CacheInterface::get($key, $default = <default>) in /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/maatwebsite/excel/src/Cache/MemoryCache.php on line 62, referer: http://192.168.0.85:8080/
[Thu Mar 02 12:08:34.350762 2023] [php:error] [pid 11648:tid 139906613344000] [client 192.168.0.117:57737] PHP Fatal error:  Uncaught Symfony\\Component\\Routing\\Exception\\RouteNotFoundException: Route [login] not defined. in /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:467\nStack trace:\n#0 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(826): Illuminate\\Routing\\UrlGenerator->route()\n#1 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/storage/framework/views/6dde8872c5517d930cf0f58d90db3feefc04eb9e.php(35): route()\n#2 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(109): require('/share/CACHEDEV...')\n#3 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(110): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()\n#4 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()\n#5 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(69): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()\n#6 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(70): Livewire\\LivewireViewCompilerEngine->evaluatePath()\n#7 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(35): Illuminate\\View\\Engines\\CompilerEngine->get()\n#8 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/View/View.php(195): Livewire\\LivewireViewCompilerEngine->get()\n#9 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\\View\\View->getContents()\n#10 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\\View\\View->renderContents()\n#11 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()\n#12 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()\n#13 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Illuminate\\Http\\Response->__construct()\n#14 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(87): Illuminate\\Routing\\ResponseFactory->make()\n#15 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(629): Illuminate\\Routing\\ResponseFactory->view()\n#16 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(554): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException()\n#17 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(460): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse()\n#18 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(377): Illuminate\\Foundation\\Exceptions\\Handler->renderExceptionResponse()\n#19 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/app/Exceptions/Handler.php(197): Illuminate\\Foundation\\Exceptions\\Handler->render()\n#20 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/app/Exceptions/Handler.php(94): App\\Exceptions\\Handler->handleWebExceptions()\n#21 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(229): App\\Exceptions\\Handler->render()\n#22 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(206): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse()\n#23 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(242): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()\n#24 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(266): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#25 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()\n#26 {main}\n\nNext Illuminate\\View\\ViewException: Route [login] not defined. (View: /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/resources/views/errors/500.blade.php) in /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:467\nStack trace:\n#0 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(106): Illuminate\\View\\Engines\\CompilerEngine->handleViewException()\n#1 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(60): Livewire\\LivewireViewCompilerEngine->handleViewException()\n#2 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(69): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()\n#3 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(70): Livewire\\LivewireViewCompilerEngine->evaluatePath()\n#4 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(35): Illuminate\\View\\Engines\\CompilerEngine->get()\n#5 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/View/View.php(195): Livewire\\LivewireViewCompilerEngine->get()\n#6 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\\View\\View->getContents()\n#7 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\\View\\View->renderContents()\n#8 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()\n#9 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()\n#10 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Illuminate\\Http\\Response->__construct()\n#11 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(87): Illuminate\\Routing\\ResponseFactory->make()\n#12 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(629): Illuminate\\Routing\\ResponseFactory->view()\n#13 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(554): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException()\n#14 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(460): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse()\n#15 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(377): Illuminate\\Foundation\\Exceptions\\Handler->renderExceptionResponse()\n#16 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/app/Exceptions/Handler.php(197): Illuminate\\Foundation\\Exceptions\\Handler->render()\n#17 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/app/Exceptions/Handler.php(94): App\\Exceptions\\Handler->handleWebExceptions()\n#18 /share/CACHEDEV1_DATA/.qpkg/Akaunting81/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(229): App\\Exceptio
```

**Comment by nephaste** [comment]
try also composer install from git master, error remain

![image](https://user-images.githubusercontent.com/3392684/222415329-985e960e-b091-4e44-afa2-fc3b16e1a8d4.png)

**Comment by ItzExotical** [comment]
Same issue. Can not get past "Settings" page on installer. Request throws 500 error. Running PHP 8.1.

**Comment by cuneytsenturk** [comment]
This commit upgrade Laravel 10 and already supports 8.1+ higher

**Comment by nephaste** [comment]
Hi 3.0.13 still having issue

provided release .. still on error 500 (with php 8.1 and 8.2.x)

from Source composer install reveal error

![image](https://user-images.githubusercontent.com/3392684/234243478-1729f1d0-3da3-45a7-a6c4-b87294f81144.png)

**Comment by nephaste** [comment]
@cuneytsenturk  from you release package did a 'composer update'

![image](https://user-images.githubusercontent.com/3392684/234496283-919336ba-dafe-4939-9e85-aeb2b12332df.png)

**Comment by nephaste** [comment]
from git clone 3.0.14

![image](https://user-images.githubusercontent.com/3392684/234497442-8acaab11-b250-4de4-af22-ce350f389efb.png)

**Comment by nephaste** [comment]
issue solved ... linked PSR extension was enable in my php.ini
