### ISSUE TITLE
Application not working with queues on Redis or database

### ISSUE THREAD

**Issue by madalinignisca** [akaunting/akaunting#2967]
### Akaunting version

3.0.14

### PHP version

8.1.18

### Operating system

Ubuntu 22.04

### Steps to reproduce

Install a fresh version of the application or reuse an already-built one.

Set queues to use Redis.

Run a worker at least.

Most jobs fail because of how models are used.

### Expected result

Run queues using Redis

### Actual result

Most jobs fail.

### Additional comments

If developers involved in testing would be confident it works, the community would kindly appreciate some tips on environment configuration to make it work.

It seems that there are some troubles regarding how Models are used.

See example of one Exception from the logs.

### Relevant log output

```shell
[2023-05-16 14:19:07] production.ERROR: Attempted to lazy load [document] on model [App\Models\Document\DocumentTotal]. {"userId":1,"exception":"[object] (Exception(code: 0): Attempted to lazy load [document] on model [App\\Models\\Document\\DocumentTotal]. at /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:665)
[stacktrace]
#0 /home/akaunting/www/app/Providers/App.php(48): report()
#1 [internal function]: App\\Providers\\App->App\\Providers\\{closure}()
#2 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(554): call_user_func()
#3 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(520): Illuminate\\Database\\Eloquent\\Model->handleLazyLoadingViolation()
#4 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(451): Illuminate\\Database\\Eloquent\\Model->getRelationValue()
#5 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2227): Illuminate\\Database\\Eloquent\\Model->getAttribute()
#6 /home/akaunting/www/vendor/genealabs/laravel-model-caching/src/Traits/ModelCaching.php(25): Illuminate\\Database\\Eloquent\\Model->__get()
#7 /home/akaunting/www/app/Models/Document/DocumentTotal.php(57): App\\Abstracts\\Model->__get()
#8 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(655): App\\Models\\Document\\DocumentTotal->getTitleAttribute()
#9 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(2071): Illuminate\\Database\\Eloquent\\Model->mutateAttribute()
#10 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(486): Illuminate\\Database\\Eloquent\\Model->transformModelValue()
#11 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(440): Illuminate\\Database\\Eloquent\\Model->getAttributeValue()
#12 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2227): Illuminate\\Database\\Eloquent\\Model->getAttribute()
#13 /home/akaunting/www/vendor/genealabs/laravel-model-caching/src/Traits/ModelCaching.php(25): Illuminate\\Database\\Eloquent\\Model->__get()
#14 /home/akaunting/www/storage/framework/views/ac19d8d37fc635f0d1f89c9efd11ea82.php(373): App\\Abstracts\\Model->__get()
#15 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(124): require('...')
#16 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(125): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()
#17 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()
#18 /home/akaunting/www/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(69): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#19 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(70): Livewire\\LivewireViewCompilerEngine->evaluatePath()
#20 /home/akaunting/www/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(35): Illuminate\\View\\Engines\\CompilerEngine->get()
#21 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/View/View.php(195): Livewire\\LivewireViewCompilerEngine->get()
#22 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\\View\\View->getContents()
#23 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\\View\\View->renderContents()
#24 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/View/Concerns/ManagesComponents.php(100): Illuminate\\View\\View->render()
#25 /home/akaunting/www/storage/framework/views/9854febe8fea79467ec7a257d17ae6c6.php(47): Illuminate\\View\\Factory->renderComponent()
#26 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(124): require('...')
#27 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(125): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()
#28 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()
#29 /home/akaunting/www/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(69): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#30 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(70): Livewire\\LivewireViewCompilerEngine->evaluatePath()
#31 /home/akaunting/www/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(35): Illuminate\\View\\Engines\\CompilerEngine->get()
#32 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/View/View.php(195): Livewire\\LivewireViewCompilerEngine->get()
#33 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\\View\\View->getContents()
#34 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\\View\\View->renderContents()
#35 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/View/Concerns/ManagesComponents.php(100): Illuminate\\View\\View->render()
#36 /home/akaunting/www/storage/framework/views/5c148b39fc635294cb978735632ded5c.php(290): Illuminate\\View\\Factory->renderComponent()
#37 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(124): require('...')
#38 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(125): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()
#39 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()
#40 /home/akaunting/www/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(69): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#41 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(70): Livewire\\LivewireViewCompilerEngine->evaluatePath()
#42 /home/akaunting/www/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(35): Illuminate\\View\\Engines\\CompilerEngine->get()
#43 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/View/View.php(195): Livewire\\LivewireViewCompilerEngine->get()
#44 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\\View\\View->getContents()
#45 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\\View\\View->renderContents()
#46 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/View/Concerns/ManagesComponents.php(100): Illuminate\\View\\View->render()
#47 /home/akaunting/www/storage/framework/views/67ee94c154cff60f9c998c6e7f583137.php(79): Illuminate\\View\\Factory->renderComponent()
#48 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(124): require('...')
#49 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(125): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()
#50 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()
#51 /home/akaunting/www/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(69): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#52 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(70): Livewire\\LivewireViewCompilerEngine->evaluatePath()
#53 /home/akaunting/www/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(35): Illuminate\\View\\Engines\\CompilerEngine->get()
#54 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/View/View.php(195): Livewire\\LivewireViewCompilerEngine->get()
#55 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\\View\\View->getContents()
#56 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\\View\\View->renderContents()
#57 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()
#58 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()
#59 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(906): Illuminate\\Http\\Response->__construct()
#60 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(875): Illuminate\\Routing\\Router::toResponse()
#61 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Routing\\Router->prepareResponse()
#62 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#63 /home/akaunting/www/vendor/santigarcor/laratrust/src/Middleware/LaratrustPermission.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#64 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laratrust\\Middleware\\LaratrustPermission->handle()
#65 /home/akaunting/www/app/Http/Middleware/Dropzone.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#66 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\Dropzone->handle()
#67 /home/akaunting/www/app/Http/Middleware/Money.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#68 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\Money->handle()
#69 /home/akaunting/www/app/Http/Middleware/DateFormat.php(40): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#70 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\DateFormat->handle()
#71 /home/akaunting/www/vendor/santigarcor/laratrust/src/Middleware/LaratrustPermission.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#72 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laratrust\\Middleware\\LaratrustPermission->handle()
#73 /home/akaunting/www/app/Http/Middleware/AdminMenu.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#74 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\AdminMenu->handle()
#75 /home/akaunting/www/app/Http/Middleware/RedirectIfWizardNotCompleted.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#76 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\RedirectIfWizardNotCompleted->handle()
#77 /home/akaunting/www/app/Http/Middleware/CheckForReadOnlyMode.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#78 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\CheckForReadOnlyMode->handle()
#79 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#80 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#81 /home/akaunting/www/app/Http/Middleware/IdentifyCompany.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#82 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\IdentifyCompany->handle()
#83 /home/akaunting/www/app/Http/Middleware/LogoutIfUserDisabled.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#84 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\LogoutIfUserDisabled->handle()
#85 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(45): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#86 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#87 /home/akaunting/www/vendor/akaunting/laravel-firewall/src/Abstracts/Middleware.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#88 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Akaunting\\Firewall\\Abstracts\\Middleware->handle()
#89 /home/akaunting/www/vendor/akaunting/laravel-firewall/src/Abstracts/Middleware.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#90 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Akaunting\\Firewall\\Abstracts\\Middleware->handle()
#91 /home/akaunting/www/vendor/akaunting/laravel-firewall/src/Abstracts/Middleware.php(32): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#92 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Akaunting\\Firewall\\Abstracts\\Middleware->handle()
#93 /home/akaunting/www/vendor/akaunting/laravel-firewall/src/Abstracts/Middleware.php(32): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#94 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Akaunting\\Firewall\\Abstracts\\Middleware->handle()
#95 /home/akaunting/www/vendor/akaunting/laravel-firewall/src/Abstracts/Middleware.php(32): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#96 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Akaunting\\Firewall\\Abstracts\\Middleware->handle()
#97 /home/akaunting/www/vendor/akaunting/laravel-firewall/src/Abstracts/Middleware.php(32): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#98 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Akaunting\\Firewall\\Abstracts\\Middleware->handle()
#99 /home/akaunting/www/vendor/akaunting/laravel-firewall/src/Abstracts/Middleware.php(32): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#100 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Akaunting\\Firewall\\Abstracts\\Middleware->handle()
#101 /home/akaunting/www/vendor/akaunting/laravel-firewall/src/Abstracts/Middleware.php(32): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#102 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Akaunting\\Firewall\\Abstracts\\Middleware->handle()
#103 /home/akaunting/www/vendor/akaunting/laravel-firewall/src/Abstracts/Middleware.php(32): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#104 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Akaunting\\Firewall\\Abstracts\\Middleware->handle()
#105 /home/akaunting/www/vendor/akaunting/laravel-firewall/src/Abstracts/Middleware.php(32): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#106 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Akaunting\\Firewall\\Abstracts\\Middleware->handle()
#107 /home/akaunting/www/vendor/akaunting/laravel-firewall/src/Abstracts/Middleware.php(32): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#108 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Akaunting\\Firewall\\Abstracts\\Middleware->handle()
#109 /home/akaunting/www/vendor/akaunting/laravel-language/src/Middleware/SetLocale.php(95): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#110 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Akaunting\\Language\\Middleware\\SetLocale->handle()
#111 /home/akaunting/www/app/Http/Middleware/AddXHeader.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#112 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\AddXHeader->handle()
#113 /home/akaunting/www/app/Http/Middleware/RedirectIfNotInstalled.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#114 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\RedirectIfNotInstalled->handle()
#115 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#116 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#117 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#118 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#119 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#120 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#121 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#122 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#123 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#124 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#125 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#126 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#127 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Pipeline\\Pipeline->then()
#128 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\\Routing\\Router->runRouteWithinStack()
#129 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\\Routing\\Router->runRoute()
#130 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(729): Illuminate\\Routing\\Router->dispatchToRoute()
#131 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#132 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#133 /home/akaunting/www/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#134 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Livewire\\DisableBrowserCache->handle()
#135 /home/akaunting/www/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#136 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#137 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#138 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#139 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#140 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#141 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#142 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#143 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#144 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#145 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#146 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#147 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#148 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#149 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#150 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#151 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustHosts.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#152 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustHosts->handle()
#153 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#154 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#155 /home/akaunting/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#156 /home/akaunting/www/index.php(27): Illuminate\\Foundation\\Http\\Kernel->handle()
#157 {main}
"}
```

**Comment by madalinignisca** [comment]
Also, emails are not sent if queue is not on `sync`, also exporting data, a notification is given that an email will be sent, but, no email, not even a file in `uploads`.

**Comment by madalinignisca** [comment]
Having `queue` on sync, everything works smoothly. But on large amounts of data, this makes most exports do long requests.

**Comment by madalinignisca** [comment]
PS: I have not done any extra settings or changes.
