### ISSUE TITLE
Error Class "MyCLabs\Enum\Enum" when trying to export transactions

### ISSUE THREAD

**Issue by christheradioguy** [akaunting/akaunting#3003]
### Akaunting version

3.0.16

### PHP version

8.1.2

### Operating system

Ubuntu 22.04

### Steps to reproduce

Navigate to Transactions, Set a filter (for instance a paid date range) and press 'Export'  Export fails with the following error "Error Class "MyCLabs\Enum\Enum""

### Expected result

CSV file is exported

### Actual result

Error Class "MyCLabs\Enum\Enum"

### Additional comments

This worked as expected in the previous version (3.0.15)

### Relevant log output

```shell
2023-07-08 20:16:04] production.ERROR: Attempted to lazy load [document] on model [App\Models\Banking\Transaction]. {"userId":2,"exception":"[object] (Exception(code: 0): Attempted to lazy load [document] on model [App\\Models\\Banking\\Transaction]. at /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:663)
[stacktrace]
#0 /var/www/akaunting/app/Providers/App.php(51): report()
#1 [internal function]: App\\Providers\\App->App\\Providers\\{closure}()
#2 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(556): call_user_func()
#3 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(522): Illuminate\\Database\\Eloquent\\Model->handleLazyLoadingViolation()
#4 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(453): Illuminate\\Database\\Eloquent\\Model->getRelationValue()
#5 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2227): Illuminate\\Database\\Eloquent\\Model->getAttribute()
#6 /var/www/akaunting/vendor/genealabs/laravel-model-caching/src/Traits/ModelCaching.php(25): Illuminate\\Database\\Eloquent\\Model->__get()
#7 /var/www/akaunting/storage/framework/views/b8a60a6a65ec44b4a87b90061b8c7ce4.php(655): App\\Abstracts\\Model->__get()
#8 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(124): require('...')
#9 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(125): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()
#10 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()
#11 /var/www/akaunting/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(69): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#12 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(70): Livewire\\LivewireViewCompilerEngine->evaluatePath()
#13 /var/www/akaunting/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(35): Illuminate\\View\\Engines\\CompilerEngine->get()
#14 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/View/View.php(195): Livewire\\LivewireViewCompilerEngine->get()
#15 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\\View\\View->getContents()
#16 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\\View\\View->renderContents()
#17 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()
#18 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()
#19 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Routing/Router.php(911): Illuminate\\Http\\Response->__construct()
#20 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Routing/Router.php(878): Illuminate\\Routing\\Router::toResponse()
#21 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Routing\\Router->prepareResponse()
#22 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#23 /var/www/akaunting/vendor/santigarcor/laratrust/src/Middleware/LaratrustPermission.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laratrust\\Middleware\\LaratrustPermission->handle()
#25 /var/www/akaunting/app/Http/Middleware/Dropzone.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\Dropzone->handle()
#27 /var/www/akaunting/app/Http/Middleware/Money.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\Money->handle()
#29 /var/www/akaunting/app/Http/Middleware/DateFormat.php(55): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\DateFormat->handle()
#31 /var/www/akaunting/vendor/santigarcor/laratrust/src/Middleware/LaratrustPermission.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laratrust\\Middleware\\LaratrustPermission->handle()
#33 /var/www/akaunting/app/Http/Middleware/AdminMenu.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\AdminMenu->handle()
#35 /var/www/akaunting/app/Http/Middleware/RedirectIfWizardNotCompleted.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\RedirectIfWizardNotCompleted->handle()
#37 /var/www/akaunting/app/Http/Middleware/CheckForReadOnlyMode.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\CheckForReadOnlyMode->handle()
#39 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#41 /var/www/akaunting/app/Http/Middleware/IdentifyCompany.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\IdentifyCompany->handle()
#43 /var/www/akaunting/app/Http/Middleware/LogoutIfUserDisabled.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\LogoutIfUserDisabled->handle()
#45 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#47 /var/www/akaunting/vendor/akaunting/laravel-firewall/src/Abstracts/Middleware.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Akaunting\\Firewall\\Abstracts\\Middleware->handle()
#49 /var/www/akaunting/vendor/akaunting/laravel-firewall/src/Abstracts/Middleware.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Akaunting\\Firewall\\Abstracts\\Middleware->handle()
#51 /var/www/akaunting/vendor/akaunting/laravel-firewall/src/Abstracts/Middleware.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Akaunting\\Firewall\\Abstracts\\Middleware->handle()
#53 /var/www/akaunting/vendor/akaunting/laravel-firewall/src/Abstracts/Middleware.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Akaunting\\Firewall\\Abstracts\\Middleware->handle()
#55 /var/www/akaunting/vendor/akaunting/laravel-firewall/src/Abstracts/Middleware.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Akaunting\\Firewall\\Abstracts\\Middleware->handle()
#57 /var/www/akaunting/vendor/akaunting/laravel-firewall/src/Abstracts/Middleware.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Akaunting\\Firewall\\Abstracts\\Middleware->handle()
#59 /var/www/akaunting/vendor/akaunting/laravel-firewall/src/Abstracts/Middleware.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Akaunting\\Firewall\\Abstracts\\Middleware->handle()
#61 /var/www/akaunting/vendor/akaunting/laravel-firewall/src/Abstracts/Middleware.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Akaunting\\Firewall\\Abstracts\\Middleware->handle()
#63 /var/www/akaunting/vendor/akaunting/laravel-firewall/src/Abstracts/Middleware.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#64 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Akaunting\\Firewall\\Abstracts\\Middleware->handle()
#65 /var/www/akaunting/vendor/akaunting/laravel-firewall/src/Abstracts/Middleware.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#66 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Akaunting\\Firewall\\Abstracts\\Middleware->handle()
#67 /var/www/akaunting/vendor/akaunting/laravel-firewall/src/Abstracts/Middleware.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#68 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Akaunting\\Firewall\\Abstracts\\Middleware->handle()
#69 /var/www/akaunting/vendor/akaunting/laravel-language/src/Middleware/SetLocale.php(95): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#70 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Akaunting\\Language\\Middleware\\SetLocale->handle()
#71 /var/www/akaunting/app/Http/Middleware/AddXHeader.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#72 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\AddXHeader->handle()
#73 /var/www/akaunting/app/Http/Middleware/RedirectIfNotInstalled.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#74 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\RedirectIfNotInstalled->handle()
#75 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#76 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#77 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#78 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#79 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#80 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#81 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#82 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#83 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#84 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#85 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#86 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#87 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Routing/Router.php(800): Illuminate\\Pipeline\\Pipeline->then()
#88 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Routing/Router.php(777): Illuminate\\Routing\\Router->runRouteWithinStack()
#89 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Routing/Router.php(741): Illuminate\\Routing\\Router->runRoute()
#90 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Routing/Router.php(730): Illuminate\\Routing\\Router->dispatchToRoute()
#91 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#92 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#93 /var/www/akaunting/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#94 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Livewire\\DisableBrowserCache->handle()
#95 /var/www/akaunting/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#96 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#97 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#98 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#99 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#100 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#101 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#102 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#103 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#104 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#105 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#106 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#107 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#108 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#109 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#110 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#111 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustHosts.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#112 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustHosts->handle()
#113 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#114 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#115 /var/www/akaunting/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#116 /var/www/akaunting/index.php(27): Illuminate\\Foundation\\Http\\Kernel->handle()
#117 {main}
"}
```

**Comment by LittleDuke** [comment]
Ran into this yesterday in Double-Entry / Chart of Accounts

**Comment by LittleDuke** [comment]
SUCCESS!  Esp after updating composer :-) 

Thanks @christheradioguy !

**Comment by cuneytsenturk** [comment]
Thank you for all your support, @christheradioguy, and this issue is solved.
