### ISSUE TITLE
Error in npm install

### ISSUE THREAD

**Issue by nikraychev** [akaunting/akaunting#3101]
### Akaunting version

3.1.4

### PHP version

8.1

### Operating system

Windows 10

### Steps to reproduce

 npm install

### Expected result

To installs any packages that it depends on

### Actual result

11396 verbose cwd C:\laragon\www\akaunting
11397 verbose Windows_NT 10.0.22621
11398 verbose node v20.10.0
11399 verbose npm  v10.2.3
11400 error code 1
11401 error path C:\laragon\www\akaunting\node_modules\node-sass
11402 error command failed
11403 error command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
11404 error Binary found at C:\laragon\www\akaunting\node_modules\node-sass\vendor\win32-x64-115\binding.node
11404 error Testing binary
11404 error Binary has a problem: Error: \\?\C:\laragon\www\akaunting\node_modules\node-sass\vendor\win32-x64-115\binding.node is not a valid Win32 application.
11404 error \\?\C:\laragon\www\akaunting\node_modules\node-sass\vendor\win32-x64-115\binding.node
11404 error     at Module._extensions..node (node:internal/modules/cjs/loader:1473:18)
11404 error     at Module.load (node:internal/modules/cjs/loader:1207:32)
11404 error     at Module._load (node:internal/modules/cjs/loader:1023:12)
11404 error     at Module.require (node:internal/modules/cjs/loader:1235:19)
11404 error     at require (node:internal/modules/helpers:176:18)
11404 error     at module.exports (C:\laragon\www\akaunting\node_modules\node-sass\lib\binding.js:19:10)
11404 error     at Object.<anonymous> (C:\laragon\www\akaunting\node_modules\node-sass\lib\index.js:13:35)
11404 error     at Module._compile (node:internal/modules/cjs/loader:1376:14)
11404 error     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
11404 error     at Module.load (node:internal/modules/cjs/loader:1207:32) {
11404 error   code: 'ERR_DLOPEN_FAILED'
11404 error }
11404 error Building the binary locally
11404 error Building: C:\Program Files\nodejs\node.exe C:\laragon\www\akaunting\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
11405 error gyp info it worked if it ends with ok
11405 error gyp verb cli [
11405 error gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
11405 error gyp verb cli   'C:\\laragon\\www\\akaunting\\node_modules\\node-gyp\\bin\\node-gyp.js',
11405 error gyp verb cli   'rebuild',
11405 error gyp verb cli   '--verbose',
11405 error gyp verb cli   '--libsass_ext=',
11405 error gyp verb cli   '--libsass_cflags=',
11405 error gyp verb cli   '--libsass_ldflags=',
11405 error gyp verb cli   '--libsass_library='
11405 error gyp verb cli ]
11405 error gyp info using node-gyp@8.4.1
11405 error gyp info using node@20.10.0 | win32 | x64
11405 error gyp verb command rebuild []
11405 error gyp verb command clean []
11405 error gyp verb clean removing "build" directory
11405 error gyp verb command configure []
11405 error gyp verb find Python Python is not set from command line or npm configuration
11405 error gyp verb find Python Python is not set from environment variable PYTHON
11405 error gyp verb find Python checking if "python3" can be used
11405 error gyp verb find Python - executing "python3" to get executable path
11405 error gyp verb find Python - "python3" is not in PATH or produced an error
11405 error gyp verb find Python checking if "python" can be used
11405 error gyp verb find Python - executing "python" to get executable path
11405 error gyp verb find Python - executable path is "C:\Python312\python.exe"
11405 error gyp verb find Python - executing "C:\Python312\python.exe" to get version
11405 error gyp verb find Python - version is "3.12.0"
11405 error gyp info find Python using Python version 3.12.0 found at "C:\Python312\python.exe"
11405 error gyp verb get node dir no --target version specified, falling back to host node version: 20.10.0
11405 error gyp verb command install [ '20.10.0' ]
11405 error gyp verb install input version string "20.10.0"
11405 error gyp verb install installing version: 20.10.0
11405 error gyp verb install --ensure was passed, so won't reinstall if already installed
11405 error gyp verb install version is already installed, need to check "installVersion"
11405 error gyp verb got "installVersion" 9
11405 error gyp verb needs "installVersion" 9
11405 error gyp verb install version is good
11405 error gyp verb get node dir target node version installed: 20.10.0
11405 error gyp verb build dir attempting to create "build" dir: C:\laragon\www\akaunting\node_modules\node-sass\build
11405 error gyp verb build dir "build" dir needed to be created? Yes
11405 error gyp verb find VS msvs_version not set from command line or npm config
11405 error gyp verb find VS VCINSTALLDIR not set, not running in VS Command Prompt
11405 error gyp verb find VS checking VS2019 (16.11.34301.259) found at:
11405 error gyp verb find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
11405 error gyp verb find VS - found "Visual Studio C++ core features"
11405 error gyp verb find VS - found VC++ toolset: v142
11405 error gyp verb find VS - missing any Windows SDK
11405 error gyp verb find VS could not find a version of Visual Studio 2017 or newer to use
11405 error gyp verb find VS looking for Visual Studio 2015
11405 error gyp verb find VS - not found
11405 error gyp verb find VS not looking for VS2013 as it is only supported up to Node.js 8
11405 error gyp ERR! find VS 
11405 error gyp ERR! find VS msvs_version not set from command line or npm config
11405 error gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
11405 error gyp ERR! find VS checking VS2019 (16.11.34301.259) found at:
11405 error gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
11405 error gyp ERR! find VS - found "Visual Studio C++ core features"
11405 error gyp ERR! find VS - found VC++ toolset: v142
11405 error gyp ERR! find VS - missing any Windows SDK
11405 error gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
11405 error gyp ERR! find VS looking for Visual Studio 2015
11405 error gyp ERR! find VS - not found
11405 error gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
11405 error gyp ERR! find VS 
11405 error gyp ERR! find VS **************************************************************
11405 error gyp ERR! find VS You need to install the latest version of Visual Studio
11405 error gyp ERR! find VS including the "Desktop development with C++" workload.
11405 error gyp ERR! find VS For more information consult the documentation at:
11405 error gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
11405 error gyp ERR! find VS **************************************************************
11405 error gyp ERR! find VS 
11405 error gyp ERR! configure error 
11405 error gyp ERR! stack Error: Could not find any Visual Studio installation to use
11405 error gyp ERR! stack     at VisualStudioFinder.fail (C:\laragon\www\akaunting\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
11405 error gyp ERR! stack     at C:\laragon\www\akaunting\node_modules\node-gyp\lib\find-visualstudio.js:75:16
11405 error gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\laragon\www\akaunting\node_modules\node-gyp\lib\find-visualstudio.js:363:14)
11405 error gyp ERR! stack     at C:\laragon\www\akaunting\node_modules\node-gyp\lib\find-visualstudio.js:71:14
11405 error gyp ERR! stack     at C:\laragon\www\akaunting\node_modules\node-gyp\lib\find-visualstudio.js:384:16
11405 error gyp ERR! stack     at C:\laragon\www\akaunting\node_modules\node-gyp\lib\util.js:54:7
11405 error gyp ERR! stack     at C:\laragon\www\akaunting\node_modules\node-gyp\lib\util.js:33:16
11405 error gyp ERR! stack     at ChildProcess.exithandler (node:child_process:430:5)
11405 error gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
11405 error gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
11405 error gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
11405 error gyp ERR! System Windows_NT 10.0.22621
11405 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\laragon\\www\\akaunting\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
11405 error gyp ERR! cwd C:\laragon\www\akaunting\node_modules\node-sass
11405 error gyp ERR! node -v v20.10.0
11405 error gyp ERR! node-gyp -v v8.4.1
11405 error gyp ERR! not ok 
11405 error Build failed with error code: 1
11406 verbose exit 1
11407 timing npm Completed in 76447ms
11408 verbose unfinished npm timer reify 1701267555187
11409 verbose unfinished npm timer reify:build 1701267626057
11410 verbose unfinished npm timer build 1701267626058
11411 verbose unfinished npm timer build:deps 1701267626059
11412 verbose unfinished npm timer build:run:postinstall 1701267626282
11413 verbose unfinished npm timer build:run:postinstall:node_modules/node-sass 1701267626295
11414 verbose code 1

### Additional comments

I removed the vendor and node_modules folders, then Akaunting the last composer.json repository, composer.lock and the package-lock.json file, but that didn't fix the problem.

### Relevant log output

```shell
11396 verbose cwd C:\laragon\www\akaunting
11397 verbose Windows_NT 10.0.22621
11398 verbose node v20.10.0
11399 verbose npm  v10.2.3
11400 error code 1
11401 error path C:\laragon\www\akaunting\node_modules\node-sass
11402 error command failed
11403 error command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
11404 error Binary found at C:\laragon\www\akaunting\node_modules\node-sass\vendor\win32-x64-115\binding.node
11404 error Testing binary
11404 error Binary has a problem: Error: \\?\C:\laragon\www\akaunting\node_modules\node-sass\vendor\win32-x64-115\binding.node is not a valid Win32 application.
11404 error \\?\C:\laragon\www\akaunting\node_modules\node-sass\vendor\win32-x64-115\binding.node
11404 error     at Module._extensions..node (node:internal/modules/cjs/loader:1473:18)
11404 error     at Module.load (node:internal/modules/cjs/loader:1207:32)
11404 error     at Module._load (node:internal/modules/cjs/loader:1023:12)
11404 error     at Module.require (node:internal/modules/cjs/loader:1235:19)
11404 error     at require (node:internal/modules/helpers:176:18)
11404 error     at module.exports (C:\laragon\www\akaunting\node_modules\node-sass\lib\binding.js:19:10)
11404 error     at Object.<anonymous> (C:\laragon\www\akaunting\node_modules\node-sass\lib\index.js:13:35)
11404 error     at Module._compile (node:internal/modules/cjs/loader:1376:14)
11404 error     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
11404 error     at Module.load (node:internal/modules/cjs/loader:1207:32) {
11404 error   code: 'ERR_DLOPEN_FAILED'
11404 error }
11404 error Building the binary locally
11404 error Building: C:\Program Files\nodejs\node.exe C:\laragon\www\akaunting\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
11405 error gyp info it worked if it ends with ok
11405 error gyp verb cli [
11405 error gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
11405 error gyp verb cli   'C:\\laragon\\www\\akaunting\\node_modules\\node-gyp\\bin\\node-gyp.js',
11405 error gyp verb cli   'rebuild',
11405 error gyp verb cli   '--verbose',
11405 error gyp verb cli   '--libsass_ext=',
11405 error gyp verb cli   '--libsass_cflags=',
11405 error gyp verb cli   '--libsass_ldflags=',
11405 error gyp verb cli   '--libsass_library='
11405 error gyp verb cli ]
11405 error gyp info using node-gyp@8.4.1
11405 error gyp info using node@20.10.0 | win32 | x64
11405 error gyp verb command rebuild []
11405 error gyp verb command clean []
11405 error gyp verb clean removing "build" directory
11405 error gyp verb command configure []
11405 error gyp verb find Python Python is not set from command line or npm configuration
11405 error gyp verb find Python Python is not set from environment variable PYTHON
11405 error gyp verb find Python checking if "python3" can be used
11405 error gyp verb find Python - executing "python3" to get executable path
11405 error gyp verb find Python - "python3" is not in PATH or produced an error
11405 error gyp verb find Python checking if "python" can be used
11405 error gyp verb find Python - executing "python" to get executable path
11405 error gyp verb find Python - executable path is "C:\Python312\python.exe"
11405 error gyp verb find Python - executing "C:\Python312\python.exe" to get version
11405 error gyp verb find Python - version is "3.12.0"
11405 error gyp info find Python using Python version 3.12.0 found at "C:\Python312\python.exe"
11405 error gyp verb get node dir no --target version specified, falling back to host node version: 20.10.0
11405 error gyp verb command install [ '20.10.0' ]
11405 error gyp verb install input version string "20.10.0"
11405 error gyp verb install installing version: 20.10.0
11405 error gyp verb install --ensure was passed, so won't reinstall if already installed
11405 error gyp verb install version is already installed, need to check "installVersion"
11405 error gyp verb got "installVersion" 9
11405 error gyp verb needs "installVersion" 9
11405 error gyp verb install version is good
11405 error gyp verb get node dir target node version installed: 20.10.0
11405 error gyp verb build dir attempting to create "build" dir: C:\laragon\www\akaunting\node_modules\node-sass\build
11405 error gyp verb build dir "build" dir needed to be created? Yes
11405 error gyp verb find VS msvs_version not set from command line or npm config
11405 error gyp verb find VS VCINSTALLDIR not set, not running in VS Command Prompt
11405 error gyp verb find VS checking VS2019 (16.11.34301.259) found at:
11405 error gyp verb find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
11405 error gyp verb find VS - found "Visual Studio C++ core features"
11405 error gyp verb find VS - found VC++ toolset: v142
11405 error gyp verb find VS - missing any Windows SDK
11405 error gyp verb find VS could not find a version of Visual Studio 2017 or newer to use
11405 error gyp verb find VS looking for Visual Studio 2015
11405 error gyp verb find VS - not found
11405 error gyp verb find VS not looking for VS2013 as it is only supported up to Node.js 8
11405 error gyp ERR! find VS 
11405 error gyp ERR! find VS msvs_version not set from command line or npm config
11405 error gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
11405 error gyp ERR! find VS checking VS2019 (16.11.34301.259) found at:
11405 error gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
11405 error gyp ERR! find VS - found "Visual Studio C++ core features"
11405 error gyp ERR! find VS - found VC++ toolset: v142
11405 error gyp ERR! find VS - missing any Windows SDK
11405 error gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
11405 error gyp ERR! find VS looking for Visual Studio 2015
11405 error gyp ERR! find VS - not found
11405 error gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
11405 error gyp ERR! find VS 
11405 error gyp ERR! find VS **************************************************************
11405 error gyp ERR! find VS You need to install the latest version of Visual Studio
11405 error gyp ERR! find VS including the "Desktop development with C++" workload.
11405 error gyp ERR! find VS For more information consult the documentation at:
11405 error gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
11405 error gyp ERR! find VS **************************************************************
11405 error gyp ERR! find VS 
11405 error gyp ERR! configure error 
11405 error gyp ERR! stack Error: Could not find any Visual Studio installation to use
11405 error gyp ERR! stack     at VisualStudioFinder.fail (C:\laragon\www\akaunting\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
11405 error gyp ERR! stack     at C:\laragon\www\akaunting\node_modules\node-gyp\lib\find-visualstudio.js:75:16
11405 error gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\laragon\www\akaunting\node_modules\node-gyp\lib\find-visualstudio.js:363:14)
11405 error gyp ERR! stack     at C:\laragon\www\akaunting\node_modules\node-gyp\lib\find-visualstudio.js:71:14
11405 error gyp ERR! stack     at C:\laragon\www\akaunting\node_modules\node-gyp\lib\find-visualstudio.js:384:16
11405 error gyp ERR! stack     at C:\laragon\www\akaunting\node_modules\node-gyp\lib\util.js:54:7
11405 error gyp ERR! stack     at C:\laragon\www\akaunting\node_modules\node-gyp\lib\util.js:33:16
11405 error gyp ERR! stack     at ChildProcess.exithandler (node:child_process:430:5)
11405 error gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
11405 error gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
11405 error gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
11405 error gyp ERR! System Windows_NT 10.0.22621
11405 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\laragon\\www\\akaunting\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
11405 error gyp ERR! cwd C:\laragon\www\akaunting\node_modules\node-sass
11405 error gyp ERR! node -v v20.10.0
11405 error gyp ERR! node-gyp -v v8.4.1
11405 error gyp ERR! not ok 
11405 error Build failed with error code: 1
11406 verbose exit 1
11407 timing npm Completed in 76447ms
11408 verbose unfinished npm timer reify 1701267555187
11409 verbose unfinished npm timer reify:build 1701267626057
11410 verbose unfinished npm timer build 1701267626058
11411 verbose unfinished npm timer build:deps 1701267626059
11412 verbose unfinished npm timer build:run:postinstall 1701267626282
11413 verbose unfinished npm timer build:run:postinstall:node_modules/node-sass 1701267626295
11414 verbose code 1
```

**Comment by nikraychev** [comment]
[Sat Dec 02 07:23:09.653607 2023] [authz_core:error] [pid 36796:tid 1360] [client 127.0.0.1:56943] AH01630: client denied by server configuration: C:/Apache24/htdocs/akaunting/.htaccess

[Sat Dec 02 07:47:09.367725 2023] [cgi:error] [pid 36796:tid 1344] (OS 2)The system cannot find the file specified.  : [client 127.0.0.1:57434] couldn't create child process: 720002: easy-install.py, referer: http://localhost/frappe_docker/

[Sat Dec 02 07:47:09.367725 2023] [cgi:error] [pid 36796:tid 1344] (OS 2)The system cannot find the file specified.  : [client 127.0.0.1:57434] AH01223: couldn't spawn child process: C:/Apache24/htdocs/frappe_docker/easy-install.py, referer: http://localhost/frappe_docker/

**Comment by nikraychev** [comment]
I tried both MySQL and MariaDB, neither database can be connected. Through PHPMyAdmin I am able to connect to both databases.

C:\Apache24\htdocs\akaunting>php artisan install --db-name="akaunting" --db-username="boot" --db-password="760130" --admin-email="afron@abv.bg" --admin-password="760130"
Setting locale en-GB
Creating database tables
Connecting to database akaunting@localhost:3306
Error: Could not connect to the database! Please, make sure the details are correct.
