### ISSUE TITLE
Error when trying to save a new invoice

### ISSUE THREAD

**Issue by tmanick01** [akaunting/akaunting#753]
Cannot save new invoices after upgrading to version 1.3.10

### Steps to reproduce the issue
On creating new invoice, and trying to save, the  request fails with a SQL exception.

### Expected result

Succesfully save the invoice

### Actual result
##Error screen . logs : 

```
[2019-02-04 15:29:18] production.ERROR: PDOException: SQLSTATE[HY000]: General error: 1364 Field 'tax_id' doesn't have a default value in /opt/bitnami/apache2/htdocs/trqAkntg/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105
Stack trace:
#0 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(105): PDOStatement->execute(NULL)
#1 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Database/Connection.php(449): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Database/Connection.php(640): Illuminate\Database\Connection->Illuminate\Database\{closure}('insert into `46...', Array)
#3 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Database/Connection.php(607): Illuminate\Database\Connection->runQueryCallback('insert into `46...', Array, Object(Closure))
#4 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Database/Connection.php(450): Illuminate\Database\Connection->run('insert into `46...', Array, Object(Closure))
#5 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Database/Connection.php(404): Illuminate\Database\Connection->statement('insert into `46...', Array)
#6 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert('insert into `46...', Array)
#7 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2133): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `46...', Array, 'id')
#8 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1251): Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#9 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(688): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#10 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(653): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(522): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#12 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(734): Illuminate\Database\Eloquent\Model->save()
#13 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Support/helpers.php(964): Illuminate\Database\Eloquent\Builder->Illuminate\Database\Eloquent\{closure}(Object(App\Models\Income\InvoiceItem))
#14 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(735): tap(Object(App\Models\Income\InvoiceItem), Object(Closure))
#15 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1374): Illuminate\Database\Eloquent\Builder->create(Array)
#16 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1386): Illuminate\Database\Eloquent\Model->__call('create', Array)
#17 /opt/bitnami/apache2/htdocs/trqAkntg/app/Jobs/Income/CreateInvoiceItem.php(206): Illuminate\Database\Eloquent\Model::__callStatic('create', Array)
#18 [internal function]: App\Jobs\Income\CreateInvoiceItem->handle()
#19 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#20 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#21 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#22 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#23 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#24 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\Income\CreateInvoiceItem))
#25 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\Income\CreateInvoiceItem))
#26 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#27 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(75): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\Income\CreateInvoiceItem))
#28 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(378): Illuminate\Bus\Dispatcher->dispatch(Object(App\Jobs\Income\CreateInvoiceItem))
#29 /opt/bitnami/apache2/htdocs/trqAkntg/app/Jobs/Income/UpdateInvoice.php(76): dispatch(Object(App\Jobs\Income\CreateInvoiceItem))
#30 [internal function]: App\Jobs\Income\UpdateInvoice->handle()
#31 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#32 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#33 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#34 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#35 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#36 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\Income\UpdateInvoice))
```

### System information (Akaunting, PHP versions)
Akaunting : Version 1.3.10
PHP : PHP (7.1.21)
Laravel (5.6.33)
SQL: MySQL (5.7.23)
Operating System : Debian (9)
Server: Apache (2.4.34)

**Comment by denisdulici** [comment]
I'm not able to reproduce such an issue. Feel free to use the forum for further help.
