### ISSUE TITLE
Error trying to access general settings on version 1.3.10

### ISSUE THREAD

**Issue by tmanick01** [akaunting/akaunting#754]
Trying to access the general settings page redirects to the error page, with an exception in logs.

### Steps to reproduce the issue

under settings, try accessing the General section, or the url https://akaunting.XXXXXX.com/settings/settings

### Expected result

general settings screen

### Actual result
error page with exception in logs

```
[2019-02-04 15:47:44] production.ERROR: ErrorException: Undefined index: financial_start in /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Support/Collection.php:1563
Stack trace:
#0 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Support/Collection.php(1563): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/opt/bitnami/ap...', 1563, Array)
#1 /opt/bitnami/apache2/htdocs/trqAkntg/storage/framework/views/445bd29fdc4ecd85b185e8c3e0ee990215c5e3e6.php(53): Illuminate\Support\Collection->offsetGet('financial_start')
#2 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(42): include('/opt/bitnami/ap...')
#3 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('/opt/bitnami/ap...', Array)
#4 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/View/View.php(137): Illuminate\View\Engines\CompilerEngine->get('/opt/bitnami/ap...', Array)
#5 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/View/View.php(120): Illuminate\View\View->getContents()
#6 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/View/View.php(85): Illuminate\View\View->renderContents()
#7 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Http/Response.php(38): Illuminate\View\View->render()
#8 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/symfony/http-foundation/Response.php(206): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#9 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Routing/Router.php(615): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#10 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Routing/Router.php(572): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#11 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/santigarcor/laratrust/src/Laratrust/Middleware/LaratrustPermission.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Laratrust\Middleware\LaratrustPermission->handle(Object(Illuminate\Http\Request), Object(Closure), Array)
#14 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/santigarcor/laratrust/src/Laratrust/Middleware/LaratrustPermission.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Laratrust\Middleware\LaratrustPermission->handle(Object(Illuminate\Http\Request), Object(Closure), Array)
#17 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 /opt/bitnami/apache2/htdocs/trqAkntg/app/Http/Middleware/AdminMenu.php(209): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\AdminMenu->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/akaunting/language/src/Middleware/SetLocale.php(94): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Akaunting\Language\Middleware\SetLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /opt/bitnami/apache2/htdocs/trqAkntg/app/Http/Middleware/LoadCurrencies.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\LoadCurrencies->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /opt/bitnami/apache2/htdocs/trqAkntg/app/Http/Middleware/LoadSettings.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\LoadSettings->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /opt/bitnami/apache2/htdocs/trqAkntg/app/Http/Middleware/AddXHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\AddXHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /opt/bitnami/apache2/htdocs/trqAkntg/app/Http/Middleware/RedirectIfNotInstalled.php(21): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\RedirectIfNotInstalled->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#37 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /opt/bitnami/apache2/htdocs/trqAkntg/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
### System information (Akaunting, PHP versions)
```

Akaunting : Version 1.3.10
PHP : PHP (7.1.21)
Laravel (5.6.33)
SQL: MySQL (5.7.23)
Operating System : Debian (9)
Server: Apache (2.4.34)

**Comment by denisdulici** [comment]
I'm not able to reproduce such an issue but you can use the forum for further help.
