### ISSUE TITLE
API returning `No query results`

### ISSUE THREAD

**Issue by alex-phillips** [akaunting/akaunting#892]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
I have an expense payment with ID `54`. If I run the following code against the API, I get the 500 error:
```php
$context = stream_context_create([
    'http' => [
        'header' => "Authorization: Basic " . base64_encode("MYUSERNAME:MYPASSWORD") . "\r\n",
    ],
]);

$url = "https://akaunting.mydomain.com/api/payments/54";
$result = json_decode(file_get_contents($url, false, $context), true);
```

### Expected result
I'd expect the payment object to be returned

### Actual result
500 error with the following resonse:
```
{"message":"No query results for model [App\\Models\\Expense\\Payment].","status_code":500,"debug":{"line":395,"file":"\/app\/akaunting\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Eloquent\/Builder.php","class":"Illuminate\\Database\\Eloquent\\ModelNotFoundException","trace":["#0 \/app\/akaunting\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/ImplicitRouteBinding.php(35): Illuminate\\Database\\Eloquent\\Builder->firstOrFail()","#1 \/app\/akaunting\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(646): Illuminate\\Routing\\ImplicitRouteBinding::resolveForRoute(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Routing\\Route))","#2 \/app\/akaunting\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Middleware\/SubstituteBindings.php(39): Illuminate\\Routing\\Router->substituteImplicitBindings(Object(Illuminate\\Routing\\Route))","#3 \/app\/akaunting\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(148): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#4 \/app\/akaunting\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#5 \/app\/akaunting\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Middleware\/ThrottleRequests.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))","#6 \/app\/akaunting\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(148): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure), '60', '1')","#7 \/app\/akaunting\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#8 \/app\/akaunting\/vendor\/dingo\/api\/src\/Http\/Middleware\/Auth.php(55): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))","#9 \/app\/akaunting\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(148): Dingo\\Api\\Http\\Middleware\\Auth->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#10 \/app\/akaunting\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#11 \/app\/akaunting\/vendor\/dingo\/api\/src\/Http\/Middleware\/PrepareController.php(45): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))","#12 \/app\/akaunting\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(148): Dingo\\Api\\Http\\Middleware\\PrepareController->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#13 \/app\/akaunting\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#14 \/app\/akaunting\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))","#15 \/app\/akaunting\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(574): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#16 \/app\/akaunting\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(533): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Dingo\\Api\\Http\\Request))","#17 \/app\/akaunting\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(511): Illuminate\\Routing\\Router->dispatchToRoute(Object(Dingo\\Api\\Http\\Request))","#18 \/app\/akaunting\/vendor\/dingo\/api\/src\/Routing\/Adapter\/Laravel.php(81): Illuminate\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))","#19 \/app\/akaunting\/vendor\/dingo\/api\/src\/Routing\/Router.php(513): Dingo\\Api\\Routing\\Adapter\\Laravel->dispatch(Object(Dingo\\Api\\Http\\Request), 'v1')","#20 \/app\/akaunting\/vendor\/dingo\/api\/src\/Http\/Middleware\/Request.php(126): Dingo\\Api\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))","#21 \/app\/akaunting\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(114): Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}(Object(Dingo\\Api\\Http\\Request))","#22 \/app\/akaunting\/vendor\/fideloper\/proxy\/src\/TrustProxies.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#23 \/app\/akaunting\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(148): Fideloper\\Proxy\\TrustProxies->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#24 \/app\/akaunting\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/TransformsRequest.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#25 \/app\/akaunting\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(148): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#26 \/app\/akaunting\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/TransformsRequest.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#27 \/app\/akaunting\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(148): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#28 \/app\/akaunting\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#29 \/app\/akaunting\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(148): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#30 \/app\/akaunting\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/CheckForMaintenanceMode.php(46): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#31 \/app\/akaunting\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(148): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#32 \/app\/akaunting\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#33 \/app\/akaunting\/vendor\/dingo\/api\/src\/Http\/Middleware\/Request.php(127): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#34 \/app\/akaunting\/vendor\/dingo\/api\/src\/Http\/Middleware\/Request.php(103): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))","#35 \/app\/akaunting\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(148): Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#36 \/app\/akaunting\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))","#37 \/app\/akaunting\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))","#38 \/app\/akaunting\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#39 \/app\/akaunting\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))","#40 \/app\/akaunting\/index.php(27): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))","#41 {main}"]}}
```

### System information (Akaunting, PHP versions)
Akaunting: 1.3.17
PHP: 7.2.22
Alpine Linux

**Comment by denisdulici** [comment]
You should pass the company id to request like:

`https://akaunting.mydomain.com/api/payments/54?company_id=1`
